spring:
  application:
    name: front
server:
  port: 8086

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

service:
  name: BANKING-MICROSERVICE