server:
  port: 8085
spring:
  main:
    web-application-type: reactive
  application:
    name: banking-microservice
  jackson:
    time-zone: UTC
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://db_bank/postgres
    user: postgres
    password: MyPostYang1994@!

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    database: POSTGRESQL
  sql:
    init:
      platform: postgres

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    enabled: true
    path: /api-docs