server:
  port: 8085
spring:
  main:
    web-application-type: reactive
  application:
    name: banking-microservice
  jackson:
    time-zone: UTC
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/banking
    password: MyPostYang1994@!
    username: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/banking
    user: postgres
    password: MyPostYang1994@!

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    database: POSTGRESQL
  sql:
    init:
      platform: postgres

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    enabled: true
    path: /api-docs