spring:
  datasource:
    url: r2dbc:postgresql://db_bank:5432/banking?connectionTimeZone=UTC
    username: postgres

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
