server:
  port: 8085
spring:
  application:
    name: banking-microservice
  springdoc:
    api-docs:
      path: /api-docs
  jackson:
    time-zone: UTC
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/banking?connectionTimeZone=UTC
    username: postgres
    password:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    database: POSTGRESQL
  sql:
    init:
      platform: postgres

