spring:
  r2dbc:
    password: MyPostYang1994@!
    url: r2dbc:postgresql://db_bank/postgres
    username: postgres

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
